== Low_Power_Multidimensional_Sorters

=== `Low Power Multidimensional Sorters using Clock Gating and Index Sorting (https://ieeexplore.ieee.org/document/10234758[Paper Link])`

`Published in: 2023 IEEE International Conference on Electronics, Computing and Communication Technologies (CONECCT)` + 
`DOI: 10.1109/CONECCT57959.2023.10234758`



`Maturity Level`: Passed Gate Level Simulations with Positive Slack for 50MHz (TODO) + 
`Collateral`: Verilog Design Files link// , SystemVerilog Layered TestBench link // link:./sdc[Constraints File]

Library: Synopsys 90nm Typical VT (saed90nm_typ.lib)

|===
|Sorter Implementation| MDSA designs 
|Bitonic (24 CAE) |link:./rtl/MDSA_bitonic[MDSA_bitonic] +
link:./rtl/MDSA_bitonic_index_merge_unit[MDSA_bitonic_index_merge] +
link:./rtl/MDSA_bitonic_index_pipeline[MDSA_bitonic_index_pipeline] 
|Hybrid (23 CAE) |link:./rtl/MDSA_hybrid[MDSA_hybrid] +
link:./rtl/MDSA_hybrid_index[MDSA_hybrid_index]
|Odd Even (19 CAE) |link:./rtl/MDSA_odd_even[MDSA_OE] +
link:./rtl/MDSA_odd_even_index[MDSA_OE_index]|
|===
Testing Methodology: link:./tb[SystemVerilog Layered Testbench] (for 100
iterations, using constraints and randomization for generating VCD)

 - We further applied clock gating to all the above designs for further
power reduction. 
 - Total 14 Implementations, Lowest Power: MDSA Bitonic with Index and
Clock Gating Lowest Area: MDSA Odd Even with Clock Gating

=== Contributing
If you would like to contribute to the existing designs, (TODO )

=== Licenses

----------------------------------------------------------------------------
Copyright (c) 2022 Samahith S A and Sai Govardhan

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:
  
The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
----------------------------------------------------------------------------
=== Background of the project

BTech ECE Capstone Project (Team: N-08, Batch of ECE 2023) at PES University, Bangalore +
Guide: Dr. Sudeendra Kumar K 
